spring:
  profiles:
    active: prod
  application:
    name: discodeit

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: Discodeit
    version: 1.7.0
    java-version: 17
    spring-boot-version: 3.4.0

logging:
  level:
    root: info
    com.sprint.mission.discodeit: debug